name: Run Zelia Bot 24/7
on:
  push:
  schedule:
    - cron: '0 */4 * * *' # Automatically reboots the cloud container every 4 hours to bypass free limitations and keep it alive

jobs:
  run-afk-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: node index.js
